[package]
name = "async-bevy-events"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy = {workspace = true}
derive_more = { version = "1.0.0", features = ["debug", "into"] }
flume = "0.11.0"
static_assertions = "1.1.0"
thiserror = "1.0.63"
