[package]
name = "async-bevy-events"
version = "0.2.3"
edition = "2021"

[dependencies]
bevy.workspace = true
flume.workspace = true
static_assertions.workspace = true
thiserror.workspace = true
derive_more.workspace = true
