[package]
name = "octo"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.16.3", features = ["derive"] }
derive-new = "0.6.0"
get-size = { version = "0.1.4", features = ["derive"] }
glam = "0.28.0"
rangemap = "1.5.1"
simba = { version = "0.9.0", features = ["libm"] }
