[package]
name = "octo"
version = "0.1.0"
edition = "2021"

[profile.bench]
opt-level = 3
debug = "full"
strip = "none"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = 'unwind'
incremental = false
codegen-units = 1
rpath = false

[dependencies]
derive-new = "0.6.0"
glam = "0.28.0"
ndarray = "0.16.0"
static_assertions = "1.1.0"
thiserror = "1.0.63"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "octree"
harness = false

[[bench]]
name = "lensed"
harness = false

[[bench]]
name = "subdiv_bench"
harness = false
