[package]
name = "event-funnel"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {workspace = true}
crossbeam = {workspace = true}
derive_more = { version = "1.0.0", features = ["debug", "into"] }
static_assertions = "1.1.0"
thiserror = "1.0.63"
